package Homework.dao;

import Homework.exception.Exception_class;
import Homework.vo.Board;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.InputMismatchException;

public class query_methods {
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    Exception_class exobj = new Exception_class();
    ArrayList<Board> boardlist = new ArrayList<Board>();
    private static ResultSet rs = null;


    public Boolean insert_db(Connection connection, Board board) throws IOException {
        String query = "INSERT INTO board_site(writer, date, title, content)" + "VALUES(?,?,?,?)";

        int confirm = Integer.parseInt(br.readLine());
        try{
            if(confirm == 1){
                //db에 저장하기
                PreparedStatement pstmt = connection.prepareStatement(query);
                //pstmt.setString(1, String.valueOf(number));
                pstmt.setString(1, board.getBwriter());
                pstmt.setString(2, String.valueOf(board.getBdate()));
                pstmt.setString(3, board.getBtitle());
                pstmt.setString(4, board.getBcontent());

                pstmt.executeUpdate();
                pstmt.close();
                return true;

            } else if (confirm == 2) {
                System.out.println();
                return true;
                //flag_c = true;
            }else {
                exobj.checkmenu(confirm);
            }
        }catch(InputMismatchException e){
           throw new InputMismatchException();
        }catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return false;
    }

    public ArrayList get_db(Connection connection){
        String query = "SELECT * FROM board_site";
        boardlist.clear();

        try{
            PreparedStatement pstmt = connection.prepareStatement(query);
            rs = pstmt.executeQuery();
            //Executes the SQL query in this PreparedStatement object and returns the ResultSet object generated by the query.
            while(rs.next()){
                //A table of data representing a database result set, which is usually generated by executing a statement that queries the database.
                Board board = new Board();
                board.setBno(rs.getByte("no"));
                board.setBwriter(rs.getString("writer"));
                board.setBdate(LocalDate.parse(rs.getString("date")));
                board.setBtitle(rs.getString("title"));

                boardlist.add(board);
            }
            return boardlist;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }





}
